import { useEffect } from "react";
import {
  Links,
  LiveReload,
  Meta,
  Outlet,
  Scripts,
  ScrollRestoration,
  useTransition,
} from "remix";
import tailwindStyles from "./styles/app.css";
// import buttonStyles from "./styles/button.css";
// import formStyles from "./styles/form.css";
import Nprogress from "nprogress";
import nprogressStyles from "../styles/nprogress.css";
import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faGlobe,
  faPaperclip,
  faCheckCircle,
  faEye,
  faEyeSlash,
  faBars,
  faChevronLeft,
  faChevronRight,
  faCircle,
  faTimesCircle,
  faArrowAltCircleRight,
  faSave,
  faInfoCircle,
  faTimes,
  faCaretUp,
  faCaretDown,
  faLifeRing,
  faPhone,
  faEnvelopeOpen,
  faNewspaper,
  faCircleNotch,
  faChevronUp,
  faChevronDown,
  faStar,
  faThumbsUp,
  faHeart,
  faTrophy,
  faPrint,
  faUpload,
  faExclamationCircle,
  faPencilAlt,
  faSignOutAlt,
  faFilter,
  faTrash,
  faSortDown,
  faSortUp,
  faSort,
  faEllipsisV,
  faEllipsisH,
  faAngleLeft,
  faAngleRight,
  faSearch,
  faDownload,
  faCalendarDay,
  faExclamationTriangle,
  faTachometerAlt,
  faUniversity,
  faTasks,
  faUserShield,
  faClipboardCheck,
  faClipboardList,
  faBook,
  faCheckSquare,
  faPlus,
  faPlusCircle,
  faPlusSquare,
  faFont,
  faAlignLeft,
  faCaretSquareDown,
  faList,
  faSortNumericDown,
  faDollarSign,
  faEnvelope,
  faLink,
  faClock,
  faSignal,
  faLock,
  faLockOpen,
  faFile,
  faFileAlt,
  faArchive,
  faArrowCircleLeft,
  faArrowCircleRight,
  faUsers,
  faUserTimes,
  faWallet,
  faTable,
  faEdit,
  faMoneyCheck,
  faBullhorn,
  faBan,
  faKey,
  faExternalLinkAlt,
  faPaintBrush,
  faArrowRight,
  faEquals,
  faCloudUploadAlt,
  faCaretRight,
  faCaretLeft,
  faShareAlt,
  faArrowUp,
  faArrowDown,
  faBookOpen,
  faChartArea,
  faArrowLeft,
  faEnvelopeOpenText,
  faCashRegister,
  faHistory,
  faSpinner,
  faDatabase,
  faPollH,
  faConciergeBell,
  faStream,
  faComments,
  faInbox,
  faHome,
  faChevronCircleDown,
  faBell,
  faWrench,
  faFolderPlus,
  faMapMarkedAlt,
  faUserLock,
  faFolderOpen,
} from "@fortawesome/free-solid-svg-icons";
import { faSquare } from "@fortawesome/free-regular-svg-icons";

library.add(
  faGlobe,
  faCheckCircle,
  faEye,
  faEyeSlash,
  faBars,
  faChevronLeft,
  faChevronRight,
  faCircle,
  faTimesCircle,
  faArrowAltCircleRight,
  faSave,
  faInfoCircle,
  faTimes,
  faCaretUp,
  faCaretDown,
  faLifeRing,
  faPhone,
  faEnvelopeOpen,
  faNewspaper,
  faCircleNotch,
  faChevronUp,
  faChevronDown,
  faStar,
  faThumbsUp,
  faHeart,
  faTrophy,
  faPrint,
  faUpload,
  faExclamationCircle,
  faPencilAlt,
  faSignOutAlt,
  faFilter,
  faTrash,
  faSortDown,
  faSortUp,
  faSort,
  faEllipsisV,
  faAngleLeft,
  faAngleRight,
  faSearch,
  faDownload,
  faCalendarDay,
  faExclamationTriangle,
  faTachometerAlt,
  faUniversity,
  faTasks,
  faUserShield,
  faClipboardCheck,
  faClipboardList,
  faBook,
  faCheckSquare,
  faSquare,
  faCloudUploadAlt,
  faPlus,
  faPlusCircle,
  faPlusSquare,
  faFont,
  faAlignLeft,
  faCaretSquareDown,
  faList,
  faSortNumericDown,
  faDollarSign,
  faEnvelope,
  faLink,
  faClock,
  faLock,
  faLockOpen,
  faSignal,
  faFile,
  faFileAlt,
  faArchive,
  faArrowCircleLeft,
  faArrowCircleRight,
  faUsers,
  faUserTimes,
  faWallet,
  faTable,
  faEdit,
  faMoneyCheck,
  faBullhorn,
  faKey,
  faBan,
  faExternalLinkAlt,
  faPaintBrush,
  faArrowRight,
  faEquals,
  faCaretRight,
  faCaretLeft,
  faShareAlt,
  faArrowUp,
  faArrowDown,
  faBookOpen,
  faChartArea,
  faArrowLeft,
  faEnvelopeOpenText,
  faCashRegister,
  faHistory,
  faSpinner,
  faDatabase,
  faPollH,
  faConciergeBell,
  faEllipsisH,
  faPaperclip,
  faStream,
  faComments,
  faInbox,
  faHome,
  faChevronCircleDown,
  faBell,
  faWrench,
  faFolderPlus,
  faMapMarkedAlt,
  faUserLock,
  faFolderOpen
);

export function meta() {
  return { title: "New Remix App" };
}

export function links() {
  return [
    { rel: "stylesheet", href: nprogressStyles },
    { rel: "stylesheet", href: tailwindStyles },
    // { rel: "stylesheet", href: buttonStyles },
    // { rel: "stylesheet", href: formStyles },
  ];
}

export default function App() {
  const transition = useTransition();
  useEffect(() => {
    if (transition.state === "loading" || transition.state === "submitting") {
      Nprogress.start();
    } else {
      Nprogress.done();
    }
  }, [transition.state]);
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <Meta />
        <Links />
      </head>
      <body>
        <Outlet />
        <ScrollRestoration />
        <Scripts />
        {process.env.NODE_ENV === "development" && <LiveReload />}
      </body>
    </html>
  );
}
